CREATE TYPE grocery as ENUM(
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE shopping_list (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name VARCHAR NOT NULL,
  price MONEY NOT NULL DEFAULT '0.00',
  date_added TIMESTAMP DEFAULT now(),
  checked BOOLEAN DEFAULT 'false',
  category grocery
);